#!/bin/bash
APOD_HOST="http://apod.nasa.gov/apod"
APOD_PAGE="archivepix.html"
APOD_URL=${APOD_HOST}/${APOD_PAGE}
PIC_FOLDER="./apod-photos"
echo "---- BEGIN"

if [ ! -d ${PIC_FOLDER} ]; then
  echo "-- Destination Folder doesn't exists"
  echo "-- Creating folder"
  mkdir ${PIC_FOLDER}
else
  echo "-- Destination Folder ok"
fi

echo "-- Scrapping site ${APOD_URL}"

STRIP_SINGLE=`wget -q ${APOD_URL} -O - | grep -o '<a.*/a>' | awk -F\" '{print $2}' | grep -v http`

for SINGLE in ${STRIP_SINGLE[@]}; 
do
  APOD_SINGLE=${APOD_HOST}/${SINGLE}
  #echo "-- Working with single page -> ${APOD_SINGLE}"
  STRIP_IMG=`wget -q ${APOD_SINGLE} -O - | grep "IMG SRC" | awk -F\" '{print $2}'`
  IMG_NAME=`wget -q ${APOD_SINGLE} -O - | grep "IMG SRC" | awk -F\" '{print $2}' | awk -F\/ '{print $3}'`
  IMG_URL=${APOD_HOST}/${STRIP_IMG}
  echo "-- Downloading ${IMG_URL}"
  wget -O ${PIC_FOLDER}/${IMG_NAME} ${IMG_URL}
done
